"""設計 Token 定義 — 單一真相來源 (Single Source of Truth)。

從 theme.py 中提取的常數定義，包含：
- PREFERRED_CJK_FONT_FAMILIES: CJK 字型偏好順序
- CJK_FONT_FAMILY_CSS: CSS font-family fallback chain
- TOKENS: 設計 Token（顏色、間距、圓角等）
- TYPOGRAPHY: 字級 scale 定義
"""

from __future__ import annotations

from ui.design_tokens import PALETTE as _P

PREFERRED_CJK_FONT_FAMILIES = (
    "Microsoft JhengHei UI",
    "Microsoft JhengHei",
    "Microsoft YaHei UI",
    "Microsoft YaHei",
    "DengXian",
    "Segoe UI",
    "PingFang TC",
    "Noto Sans TC",
    "Noto Sans HK",
    "Noto Sans CJK TC",
    "Source Han Sans TC",
    "Noto Sans CJK SC",
    "Source Han Sans SC",
    "WenQuanYi Zen Hei",
    "Arial Unicode MS",
)

# Single source of truth for the CJK font fallback chain. ncr.ui.ui_style imports
# this instead of keeping a divergent second copy (AGENTS.md single-source rule).
CJK_FONT_FAMILY_CSS = (
    ", ".join(f"'{_family}'" for _family in PREFERRED_CJK_FONT_FAMILIES) + ", sans-serif"
)

# Values re-sourced from the unified design_tokens.PALETTE (keys unchanged, so
# every QSS selector below recolors automatically). See ui/design_tokens.py.
TOKENS = {
    "brand_blue": _P["primary"],
    "brand_primary": _P["primary_hover"],
    "brand_navy": _P["hero_start"],
    "brand_cyan": _P["accent_cyan"],
    "accent_report": _P["accent_report"],
    "page_bg": _P["app_bg"],
    "panel_bg": _P["surface"],
    "panel_alt_bg": _P["surface_alt"],
    "subtle_bg": _P["surface_sunken"],
    "surface_hover": _P["surface_hover"],
    "surface_active": _P["surface_active"],
    "surface_accent": _P["surface_accent"],
    "surface_warning": _P["pending_bg"],
    "surface_danger": _P["danger_bg"],
    "focus_ring": _P["focus_ring"],
    "border": _P["border"],
    "border_soft": _P["border_soft"],
    "border_strong": _P["border_strong"],
    "grid": _P["grid"],
    "text_primary": _P["text_primary"],
    "text_secondary": _P["text_secondary"],
    "text_muted": _P["text_muted"],
    "text_disabled": _P["text_disabled"],
    "primary_btn": _P["primary"],
    "primary_btn_hover": _P["primary_hover"],
    "primary_faint": _P["primary_faint"],
    "selection_bg": _P["selection_bg"],
    "danger": _P["danger_fg"],
    "danger_border": _P["danger_border"],
    "danger_hover": _P["danger_bg"],
    "warning": _P["pending_fg"],
    "warning_bg": _P["pending_bg"],
    "warning_border": _P["pending_border"],
    "success": _P["success_fg"],
    "success_bg": _P["success_bg"],
    "info": _P["info_fg"],
    "info_bg": _P["info_bg"],
    "info_border": _P["info_border"],
    "status_pending_fg": _P["pending_fg"],
    "status_pending_bg": _P["pending_bg"],
    "status_pending_border": _P["pending_border"],
    "status_pending_chart": _P["pending_chart"],
    "status_success_fg": _P["success_fg"],
    "status_success_bg": _P["success_bg"],
    "status_success_border": _P["success_border"],
    "status_success_chart": _P["success_chart"],
    "status_danger_fg": _P["danger_fg"],
    "status_danger_bg": _P["danger_bg"],
    "status_danger_border": _P["danger_border"],
    "status_danger_chart": _P["danger_chart"],
    "status_info_fg": _P["info_fg"],
    "status_info_bg": _P["info_bg"],
    "status_info_border": _P["info_border"],
    "status_info_chart": _P["info_chart"],
    "status_unknown_fg": _P["na_fg"],
    "status_unknown_bg": _P["na_bg"],
    "status_unknown_border": _P["na_border"],
    "status_unknown_chart": _P["na_chart"],
    "status_na_fg": _P["na_fg"],
    "status_na_bg": _P["na_bg"],
    "status_na_border": _P["na_border"],
    "status_na_chart": _P["na_chart"],
    "chart_grid": _P["chart_grid"],
    "chart_axis_text": _P["chart_axis"],
    "chart_plot_bg": _P["chart_plot_bg"],
    "radius_sm": _P["radius_sm"],
    "radius_md": _P["radius_md"],
    "radius_lg": _P["radius_lg"],
    "toolbar_bar_bg": _P["surface_alt"],
    "toolbar_bar_border": _P["border_soft"],
    "toolbar_primary": _P["primary"],
    "toolbar_primary_hover": _P["primary_hover"],
    "toolbar_secondary_bg": _P["surface"],
    "toolbar_secondary_text": _P["text_secondary"],
    "toolbar_secondary_hover": _P["surface_hover"],
    "toolbar_ghost_bg": _P["surface_alt"],
    "toolbar_ghost_text": _P["text_secondary"],
    "toolbar_ghost_border": _P["border"],
    "nav_bg": _P["app_bg"],
    "nav_bg_hover": _P["surface_sunken"],
    "nav_text": _P["text_secondary"],
    "nav_text_active": _P["text_primary"],
    # Hero Banner
    "hero_gradient_start": _P["hero_start"],
    "hero_gradient_mid": _P["hero_mid"],
    "hero_gradient_end": _P["hero_end"],
    "hero_title_color": _P["text_inverse"],
    "hero_subtitle_color": _P["on_hero_subtitle"],
    "hero_meta_text": _P["on_hero_meta"],
    # 主導覽 Tab Bar （深色）
    "nav_dark_bg": _P["sidebar_bg"],
    "nav_dark_hover_bg": _P["sidebar_hover"],
    "nav_dark_text": _P["sidebar_text"],
    "nav_dark_text_active": _P["sidebar_text_active"],
    "nav_dark_selected_indicator": _P["sidebar_indicator"],
    "filter_active_bg": _P["primary_faint"],
    "filter_active_border": _P["accent_cyan"],
    "filter_active_text": _P["info_fg"],
    "filter_hover_bg": _P["surface_hover"],
    "empty_state_bg": _P["surface_alt"],
    "empty_state_border": _P["border"],
    "attachment_bg": _P["surface_alt"],
    "attachment_hover_bg": _P["primary_faint"],
    "attachment_selected_bg": _P["selection_bg"],
    "attachment_selected_border": _P["accent_cyan"],
    # Mitcorp 品牌第二色（雙色品牌點：深青 + 綠）
    "brand_green": _P["brand_green"],
    # 左側導覽側欄
    "sidebar_bg": _P["sidebar_bg"],
    "sidebar_panel": _P["sidebar_panel"],
    "sidebar_active_bg": _P["sidebar_active_bg"],
    "sidebar_hover_bg": _P["sidebar_hover"],
    "sidebar_active_indicator": _P["sidebar_indicator"],
    "sidebar_text": _P["sidebar_text"],
    "sidebar_text_active": _P["sidebar_text_active"],
    "sidebar_muted": _P["sidebar_muted"],
    "sidebar_divider": _P["sidebar_divider"],
    # 頁面頂部標題列
    "page_header_bg": _P["surface"],
    "page_header_shadow": _P["border_soft"],
    # 逾期警示橫幅
    "overdue_banner_bg": _P["danger_bg"],
    "overdue_banner_border": _P["danger_border"],
    "overdue_banner_text": _P["danger_fg"],
    "overdue_banner_link": _P["info_fg"],
}

TYPOGRAPHY = {
    "font_family": ", ".join(f'"{_family}"' for _family in PREFERRED_CJK_FONT_FAMILIES) + ", sans-serif",
    "base": 13,
    "brand_title": 22,
    "nav_tab": 13,
    "page_title": 24,
    "section_title": 16,
    "helper_text": 13,
    "kpi_title": 13,
    "kpi_value": 26,
    "group_box_title": 13,
    "tab_label": 13,
    "divider_title": 16,
    "mono": 11,
    "hero_title": 24,
    "hero_subtitle": 13,
    "hero_meta": 12,
    # Generic scale shared across dialogs / badges / inline labels
    "caption": 11,
    "body_small": 12,
    "body": 13,
    "label_strong": 14,
    "icon_large": 18,
}