"""Shared supplier category labels for master data and NCR."""

from __future__ import annotations

from typing import Any

SUPPLIER_CATEGORY_RAW_MATERIAL = "原物料供應商"
SUPPLIER_CATEGORY_OUTSOURCE_FACTORY = "委外加工"
LEGACY_SUPPLIER_CATEGORY_FORMAL = "正式供應商"
LEGACY_SUPPLIER_CATEGORY_OUTSOURCE = "委外供應商"
LEGACY_SUPPLIER_CATEGORY_RAW_MATERIAL_V1 = "原材料供應商"
LEGACY_SUPPLIER_CATEGORY_OUTSOURCE_FACTORY_V1 = "委外加工廠"

SUPPLIER_CATEGORY_OPTIONS: tuple[str, ...] = (
    SUPPLIER_CATEGORY_RAW_MATERIAL,
    SUPPLIER_CATEGORY_OUTSOURCE_FACTORY,
)

LEGACY_SUPPLIER_CATEGORY_MAP: dict[str, str] = {
    LEGACY_SUPPLIER_CATEGORY_FORMAL: SUPPLIER_CATEGORY_RAW_MATERIAL,
    LEGACY_SUPPLIER_CATEGORY_OUTSOURCE: SUPPLIER_CATEGORY_OUTSOURCE_FACTORY,
    LEGACY_SUPPLIER_CATEGORY_RAW_MATERIAL_V1: SUPPLIER_CATEGORY_RAW_MATERIAL,
    LEGACY_SUPPLIER_CATEGORY_OUTSOURCE_FACTORY_V1: SUPPLIER_CATEGORY_OUTSOURCE_FACTORY,
}

SUPPLIER_CATEGORY_RENAME_META_KEY = "supplier_category_rename_v1"
SUPPLIER_CATEGORY_RENAME_V2_META_KEY = "supplier_category_rename_v2"


def normalize_supplier_category(value: Any) -> str:
    text = str(value or "").strip()
    if text in SUPPLIER_CATEGORY_OPTIONS:
        return text
    mapped = LEGACY_SUPPLIER_CATEGORY_MAP.get(text)
    if mapped:
        return mapped
    return SUPPLIER_CATEGORY_RAW_MATERIAL
